[package]
name = "secret_santa"
version = "0.1.0"
authors = ["han-tyumi <mmchamp95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.7.1"
rand = "0.8.0"
